name = "dex-worker"
main = "src/server.ts"
compatibility_date = "2024-03-01"
workers_dev = true

kv_namespaces = [
  { binding = "TX_QUEUE", id = "<QUEUE_NAMESPACE_ID>" }
]

[build]
command = "npm run build && wrangler types"

[vars]
KV_ENCRYPTION_KEY = "@kv_encryption_key"
BTC_PRIVATE_KEY = "@btc_key::2"
ETH_SIGNER_KEY = "@eth_signer::3"
RANGO_API_KEY = "@rango_api_key"
WALLETCONNECT_PROJECT_ID = "@wc_project_id"

[durable_objects]
bindings = [
  { name = "TRANSACTION_STORE", class_name = "TransactionStore" }
]
